[package]
name = "hrtor"
authors = ["haruki7049 <tontonkirikiri@gmail.com>"]
version = "0.2.0-dev"
description = "A scalable line editor"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/haruki7049/hrtor"
repository = "https://github.com/haruki7049/hrtor"
keywords = ["editor", "text-editor"]
categories = ["text-editors"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
linefeed = "0.6.0"
rlua = "0.19.7"
file_loader = { path = "file_loader" }
cli = { path = "cli" }
constants = { path = "constants" }
processor = { path = "processor" }

[workspace]

members = [
  "cli",
  "constants",
  "file_loader",
  "file_loader/file_loader_derive",
  "processor",
]
