[toolchain]
channel = "1.86.0"
components = ["rust-src", "rust-analyzer"]
targets = [
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
]
profile = "default"
