[package]
name = "hrtor_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
pest = "2.8.0"
pest_derive = "2.8.0"
ropey = { version = "1.6.1", optional = true }
thiserror = "2.0.12"

[features]
default = []
ropey = ["dep:ropey"]
