name: main-branch-builder
on:
  push:
    branches:
      - "main"
permissions: {}

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run nix-build .#hrtor
        run: nix build .#hrtor
      - name: Upload executable for x86_64-linux
        uses: actions/upload-artifact@v4
        with:
          name: hrtor-x86_64-linux-bin
          path: result
